apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  # region: ap-south-1
  region: us-west-2
  version: "1.25"

managedNodeGroups:
  - name: ng-dedicated-1
    instanceType: t3a.medium
    desiredCapacity: 1
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key