apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
spec:
  serviceAccountName: s3-list-sa
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
      - sleep
      - "360000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

